import type { Catalogue } from './strings'

/**
 * Arabic catalogue — Jordanian shop vernacular where it applies
 * (تيل، ترصيص، بنشر، ردييتر) and MSA for the interface itself.
 *
 * Terminology decisions, changeable in one place:
 *   Job      = أمر عمل   (work order — what garage software uses)
 *   Customer = زبون      (the shop word; عميل is bank-speak)
 *   Dashboard= الرئيسية
 *   Figures stay Latin digits; currency shown as د.أ
 *
 * Plural sets carry .two/.few/.many where the count is user-visible.
 * Placeholders ({name}, {count}, …) are inferred from key names — run a
 * parity check against the English file before trusting them.
 */
export const ar: Catalogue = {
  // ── shell ─────────────────────────────────────────────────────────────
  'nav.sections': 'الأقسام',
  'nav.dashboard': 'الرئيسية',
  'nav.newJob': 'أمر عمل جديد',
  'nav.jobs': 'أوامر العمل',
  'nav.customers': 'الزبائن',
  'nav.reminders': 'التذكيرات',
  'nav.services': 'الخدمات',
  'nav.stats': 'الإحصائيات',
  'brand.name': 'GRAND PRIX',
  'brand.alt': 'غراند بري لخدمات السيارات',
  'nav.language': 'English',

  'app.loading': 'جاري التحميل…',
  'app.signOut': 'تسجيل الخروج',
  'app.signingOut': 'جاري الخروج…',
  'app.noStaffTitle': 'الحساب غير مرتبط',
  'app.noStaffBody': 'هذا الحساب ({email}) غير مرتبط بسجل موظف بعد.',

  // ── sign in ───────────────────────────────────────────────────────────
  'login.title': 'تسجيل الدخول',
  'login.subtitle': 'غراند بري لخدمات السيارات',
  'login.email': 'البريد الإلكتروني',
  'login.password': 'كلمة المرور',
  'login.submit': 'دخول',
  'login.submitting': 'جاري الدخول…',
  'login.needBoth': 'أدخل البريد الإلكتروني وكلمة المرور.',
  'login.needEmail': 'أدخل البريد الإلكتروني.',
  'login.needPassword': 'أدخل كلمة المرور.',

  // ── shared actions and states ─────────────────────────────────────────
  'action.close': 'إغلاق',
  'action.cancel': 'إلغاء',
  'action.change': 'تغيير',
  'action.edit': 'تعديل',
  'action.remove': 'إزالة',
  'action.saveChanges': 'حفظ التغييرات',
  'action.saving': 'جاري الحفظ…',
  'action.tryAgain': 'حاول مرة أخرى',
  'action.seeAll': 'عرض الكل',
  'common.optional': 'اختياري',
  'common.notRecorded': 'غير مسجّل',
  'common.notSet': 'غير محدد',
  'common.km': 'كم',
  // ── lib: vehicles, odometer, contact health, periods ───────────────────
  'customer.unnamed': 'بدون اسم',
  'vehicle.noPlate': 'بدون لوحة',
  'vehicle.notLinked': 'بدون مركبة مرتبطة',
  'vehicle.numbered': 'مركبة {n}',
  'vehicle.numberedNamed': 'مركبة {n} ({label})',
  'vehicle.badYear': 'سنة الصنع غير صالحة.',
  'vehicle.badOdometer': 'قراءة العداد غير صالحة.',

  'odometer.lower': 'القراءة أقل من قراءة المركبة الحالية — عادةً خطأ إدخال، إلا إذا غُيّر العداد.',
  'odometer.jump': 'القراءة أعلى بكثير من الحالية — تأكد من عدد الخانات.',

  'contact.failed': 'آخر محاولة تواصل فشلت',
  'contact.noPhone': 'بدون رقم هاتف',
  'contact.noOptIn': 'بدون موافقة واتساب',

  'period.thisMonth': 'هذا الشهر',
  'period.last3Months': 'آخر 3 أشهر',
  'period.thisYear': 'هذه السنة',
  'period.allTime': 'كل الفترات',

  'month.1': 'يناير',
  'month.2': 'فبراير',
  'month.3': 'مارس',
  'month.4': 'أبريل',
  'month.5': 'مايو',
  'month.6': 'يونيو',
  'month.7': 'يوليو',
  'month.8': 'أغسطس',
  'month.9': 'سبتمبر',
  'month.10': 'أكتوبر',
  'month.11': 'نوفمبر',
  'month.12': 'ديسمبر',
  // ── line editors: prices, fluid, tires ─────────────────────────────────
  'price.parts': 'القطع',
  'price.labour': 'الأجرة',
  'price.sub': 'المقاول',
  'price.lineTotal': 'إجمالي البند',

  'fluid.type': 'النوع',
  'fluid.grade': 'الدرجة',
  'fluid.brand': 'الماركة',
  'fluid.quantity': 'الكمية',

  'tire.quantity': 'العدد',
  'tire.brand': 'الماركة',
  'tire.size': 'المقاس',
  'tire.sizePlaceholder': '225/50/17',
  'tire.dot': 'سنة DOT',
  'tire.dotHint': 'مثال: 2025 أو الرمز الكامل 1225',
  'tire.dotPlaceholder': '2025',
  'tire.condition': 'الحالة',
  'tire.runFlat': 'رن فلات',
  'tire.fittedBefore': 'مقاسات سابقة لهذه المركبة',
  'tire.lastFitted': 'آخر تركيب: {brand}',

  // ── vehicle form ───────────────────────────────────────────────────────
  'vehicleForm.plate': 'رقم اللوحة',
  'vehicleForm.platePlaceholder': '21-45678',
  'vehicleForm.vin': 'رقم الشاصي (VIN)',
  'vehicleForm.make': 'الماركة',
  'vehicleForm.model': 'الموديل',
  'vehicleForm.year': 'سنة الصنع',
  'vehicleForm.yearPlaceholder': '2019',
  'vehicleForm.category': 'الفئة',
  'vehicleForm.odometer': 'العداد',
  'vehicleForm.odometerPlaceholder': '84210',
  'vehicleForm.addMake': '+ إضافة ماركة',
  'vehicleForm.newTitle': 'مركبة جديدة',
  'vehicleForm.editTitle': 'تعديل المركبة',
  'vehicleForm.save': 'حفظ المركبة',
  'vehicleForm.needSomething': 'أدخل معلومة واحدة على الأقل عن المركبة.',
  'vehicleForm.saveFailed': 'تعذّر حفظ المركبة.',

  // ── add make ───────────────────────────────────────────────────────────
  'make.title': 'ماركة جديدة',
  'make.label': 'اسم الماركة',
  'make.placeholder': 'مثال: Jetour',
  'make.needName': 'أدخل اسم الماركة.',
  'make.needLatin': 'اكتب الاسم بأحرف لاتينية.',
  'make.note': 'ستظهر الماركة في القائمة لجميع المستخدمين.',
  'make.save': 'حفظ الماركة',
  'make.saving': 'جاري الحفظ…',
  // ── odometer hint ──────────────────────────────────────────────────────
  'odoHint.none': 'لا توجد قراءة عداد لهذا الأمر أو لمركبته.',
  'odoHint.onJob': 'على هذا الأمر',
  'odoHint.onVehicle': 'على المركبة',
  'odoHint.nowAt': 'حاليًا عند {km} كم',

  // ── mutes ──────────────────────────────────────────────────────────────
  'mute.title': 'كتم التذكيرات',
  'mute.scope': 'ماذا تريد كتمه',
  'mute.scopeService': 'خدمة واحدة',
  'mute.scopeAll': 'كل التذكيرات',
  'mute.service': 'الخدمة',
  'mute.chooseService': 'اختر خدمة',
  'mute.needService': 'اختر الخدمة المراد كتمها.',
  'mute.reason': 'السبب',
  'mute.reasonPlaceholder': 'طلب عدم التذكير',
  'mute.note': 'الكتم يلغي أي تذكير من هذا النوع معلّق حاليًا.',
  'mute.nothingLeft': 'لا يوجد شيء معلّق يمكن كتمه خدمةً بخدمة. كتم الكل يغطي أيضًا أي تذكيرات تُرفع لاحقًا.',
  'mute.allDone': 'كل شيء مكتوم لهذا الزبون. ألغِ كتم شيء أولًا لتغيير الإعداد.',
  'mute.blanketInPlace': 'كل التذكيرات مكتومة حاليًا. كتم خدمة بعينها يُبقيها مكتومة إذا أُزيل الكتم الشامل لاحقًا.',
  'mute.alreadyAll': 'الكتم الشامل مفعّل بالفعل.',
  'mute.submit': 'كتم',
  'mute.submitting': 'جاري الكتم…',

  // ── customer form ──────────────────────────────────────────────────────
  'customerForm.newTitle': 'زبون جديد',
  'customerForm.editTitle': 'تعديل الزبون',
  'customerForm.nameEn': 'الاسم بالإنجليزية',
  'customerForm.nameEnHint': 'يكفي أحد الاسمين',
  'customerForm.nameAr': 'الاسم بالعربية',
  'customerForm.nameArHint': 'يكفي أحد الاسمين',
  'customerForm.phone': 'رقم الهاتف',
  'customerForm.phoneHint': 'مطلوب لإرسال التذكيرات',
  'customerForm.phonePlaceholder': '079 000 0000',
  'customerForm.optIn': 'موافق على استلام تذكيرات واتساب',
  'customerForm.periodic': 'زبون دوري',
  'customerForm.source': 'المصدر',
  'customerForm.sourceHint': 'كيف وصلنا هذا الزبون',
  'customerForm.notes': 'ملاحظات',
  'customerForm.needIdentity': 'الزبون بحاجة إلى اسم أو رقم هاتف على الأقل.',
  'customerForm.saveFailed': 'تعذّر حفظ الزبون.',
  'customerForm.changesFailed': 'تعذّر حفظ التغييرات.',
  'customerForm.save': 'حفظ الزبون',
  'customerForm.retryVehicles': 'إعادة محاولة المركبات',
  'customerForm.vehicleLegend': 'المركبة',
  'customerForm.vehicleSaved': 'تم الحفظ',
  'customerForm.addAnotherVehicle': '+ إضافة مركبة أخرى',
  'customerForm.vehiclesFailed.one': 'تعذّر حفظ مركبة واحدة:',
  'customerForm.vehiclesFailed.two': 'تعذّر حفظ مركبتين:',
  'customerForm.vehiclesFailed.few': 'تعذّر حفظ {count} مركبات:',
  'customerForm.vehiclesFailed.many': 'تعذّر حفظ {count} مركبة:',
  'customerForm.vehiclesFailed.other': 'تعذّر حفظ {count} مركبة:',
  'customerForm.partialSave': 'تم حفظ {name}، لكن تعذّرت إضافة المركبة:',
  // ── service form and picker ────────────────────────────────────────────
  'serviceForm.title': 'خدمة جديدة',
  'serviceForm.titleInCategory': 'خدمة جديدة · {category}',
  'serviceForm.category': 'الفئة',
  'serviceForm.chooseCategory': 'اختر فئة',
  'serviceForm.needCategory': 'اختر الفئة.',
  'serviceForm.translateEmpty': '',
  'serviceForm.namePlaceholder': 'مثال: غسيل ردييتر',
  'serviceForm.name': 'اسم الخدمة',
  'serviceForm.needName': '',
  'serviceForm.englishName': '',
  'serviceForm.englishNameHint': '',
  'serviceForm.needEnglish': '',
  'serviceForm.translateFailed': '',
  'serviceForm.price': 'السعر المعتاد',
  'serviceForm.pricePlaceholder': '0.000',
  'serviceForm.badPrice': 'سعر غير صالح.',
  'serviceForm.remind': 'جدولة تذكير بعد هذه الخدمة',
  'serviceForm.intervalKm': 'المسافة المعتادة',
  'serviceForm.intervalMonths': 'المدة المعتادة',
  'serviceForm.months': 'شهر',
  'serviceForm.kmPlaceholder': '5000',
  'serviceForm.monthsPlaceholder': '6',
  'serviceForm.badInterval': 'قيمة غير صالحة.',
  'serviceForm.needInterval': 'حدد مسافة أو مدة أو كليهما.',
  'serviceForm.reminderNote': 'هذه قيم افتراضية تُعبّأ تلقائيًا عند إدخال الأمر — بند الأمر هو ما يُنشئ التذكير فعليًا.',
  'serviceForm.usesFluid': 'هذه الخدمة تستهلك سائلًا',
  'serviceForm.fluidUnit': 'وحدة القياس',
  'serviceForm.liters': 'لتر',
  'serviceForm.grams': 'غرام',
  'serviceForm.typeList': 'قائمة النوع',
  'serviceForm.noTypeList': 'بدون قائمة قياسية',
  'serviceForm.gradeList': 'قائمة الدرجة',
  'serviceForm.noGradeList': 'بدون قائمة درجات',
  'serviceForm.fluidNote': 'بنود هذه الخدمة ستطلب الماركة والكمية، والنوع أو الدرجة حيثما اختيرت قائمة.',
  'serviceForm.save': 'حفظ الخدمة',
  'serviceForm.saveFailed': 'تعذّر حفظ الخدمة.',

  'servicePicker.title': 'إضافة بند',
  'servicePicker.filterByCategory': 'تصفية حسب الفئة',
  'servicePicker.all': 'الكل',
  'servicePicker.search': 'ابحث عن خدمة',
  'servicePicker.common': 'الأكثر استخدامًا',
  'servicePicker.noMatch': 'لا توجد خدمة مطابقة.',

  // ── services screen ────────────────────────────────────────────────────
  'services.loading': 'جاري تحميل الخدمات…',
  'services.loadFailed': 'تعذّر تحميل الخدمات.',
  'services.catalogue': 'دليل الخدمات',
  'services.count.one': 'خدمة واحدة',
  'services.count.two': 'خدمتان',
  'services.count.few': '{count} خدمات',
  'services.count.many': '{count} خدمة',
  'services.count.other': '{count} خدمة',
  'services.noCategories': 'لا توجد فئات.',
  'services.emptyCategory': 'لا شيء هنا بعد.',
  'services.addTo': 'إضافة خدمة إلى {category}',
  'services.reminderRule': 'تذكير: {rule}',
  'services.reminderNoInterval': 'تذكير: بدون فترة محددة',
  'common.currency': 'د.أ',
  'common.noPhone': 'بدون هاتف',

  // ── dashboard ──────────────────────────────────────────────────────────
  'dash.loadFailed': 'تعذّر تحميل الرئيسية.',
  'dash.jobsToday': 'أوامر اليوم',
  'dash.revenueThisMonth': 'إيراد الشهر',
  'dash.remindersDue': 'تذكيرات مستحقة',
  'dash.customers': 'الزبائن',
  'dash.recentJobs': 'أحدث الأوامر',
  'dash.noJobs': 'لا أوامر بعد.',
  'dash.noLines': 'بدون بنود',
  'dash.nothingDue': 'لا شيء مستحق قريبًا.',
  'dash.unknownCustomer': 'زبون غير معروف',
  'dash.unknownService': 'خدمة غير معروفة',
  'dash.contactHealth': 'حالة التواصل',
  'dash.contactHealthNote': 'لا يمكن إرسال تذكيرات لهؤلاء حتى تُحل المشكلة.',

  // ── stats ──────────────────────────────────────────────────────────────
  'stats.period': 'الفترة',
  'stats.loadFailed': 'تعذّر تحميل الإحصائيات.',
  'stats.revenue': 'الإيراد',
  'stats.jobs': 'الأوامر',
  'stats.averageJob': 'متوسط الأمر',
  'stats.activeCustomers': 'زبائن نشطون',
  'stats.byCategory': 'الإيراد حسب الفئة',
  'stats.withRevenue': '{count} فئة لها إيراد',
  'stats.noRevenue': 'لا إيراد في هذه الفترة.',
  'stats.onlyOneCategory': 'فئة واحدة فقط لها إيراد.',
  'stats.overTime': 'الإيراد عبر الزمن',
  'stats.monthsWithJobs.one': 'شهر واحد فيه أوامر',
  'stats.monthsWithJobs.two': 'شهران فيهما أوامر',
  'stats.monthsWithJobs.few': '{count} أشهر فيها أوامر',
  'stats.monthsWithJobs.many': '{count} شهرًا فيها أوامر',
  'stats.monthsWithJobs.other': '{count} شهر فيها أوامر',
  'stats.noJobsInPeriod': 'لا أوامر في هذه الفترة.',
  'stats.onlyOneMonth': 'شهر واحد فقط فيه أوامر حتى الآن ({month}) — الاتجاه يحتاج شهرين على الأقل.',
  'stats.topByRevenue': 'الأعلى إيرادًا',
  'stats.topByFrequency': 'الأكثر تكرارًا',
  'stats.shown': 'أعلى {count}',
  'stats.noServices': 'لا خدمات بعد.',
  'stats.onlyOneService': 'خدمة واحدة فقط.',
  'stats.timesDone': 'مرات التنفيذ',
  'stats.times.one': 'مرة واحدة',
  'stats.times.two': 'مرتان',
  'stats.times.few': '{count} مرات',
  'stats.times.many': '{count} مرة',
  'stats.times.other': '{count} مرة',
  'stats.retention': 'زبائن جدد وعائدون',
  'stats.noneActive': 'لا نشاط في هذه الفترة.',
  'stats.onlyOneActiveMonth': 'شهر نشط واحد فقط.',
  'stats.new': 'جدد',
  'stats.returning': 'عائدون',
  'stats.lapsed': 'زبائن منقطعون',
  'stats.lapsedNote': 'أكثر من 180 يومًا منذ آخر زيارة، مرتبون حسب إجمالي إنفاقهم.',
  'stats.noLapsed': 'لا زبائن منقطعين.',
  'stats.daysSince': '{count} يومًا منذ آخر زيارة',
  // ── customers screen ───────────────────────────────────────────────────
  'customers.loading': 'جاري تحميل الزبائن…',
  'customers.loadFailed': 'تعذّر تحميل الزبائن.',
  'customers.search': 'ابحث بالاسم أو الهاتف',
  'customers.searchLabel': 'بحث الزبائن',
  'customers.make': 'الماركة',
  'customers.anyMake': 'كل الماركات',
  'customers.add': '+ زبون جديد',
  'customers.none': 'لا زبائن بعد.',
  'customers.noneWithMake': 'لا زبائن لديهم {make}.',
  'customers.noMakeMatch': 'لا نتيجة لهذا البحث مع هذه الماركة.',
  'customers.noMatch': 'لا زبون يطابق "{q}".',
  'customers.optedIn': 'موافق واتساب',
  'customers.notOptedIn': 'بدون موافقة',
  'customers.vehicles.one': 'مركبة واحدة',
  'customers.vehicles.two': 'مركبتان',
  'customers.vehicles.few': '{count} مركبات',
  'customers.vehicles.many': '{count} مركبة',
  'customers.vehicles.other': '{count} مركبة',
  'customers.jobs.one': 'أمر واحد',
  'customers.jobs.two': 'أمران',
  'customers.jobs.few': '{count} أوامر',
  'customers.jobs.many': '{count} أمرًا',
  'customers.jobs.other': '{count} أمر',

  'detail.noPhoneOnFile': 'لا رقم هاتف مسجّل',
  'detail.since': 'زبون منذ {date}',
  'detail.optedInWhatsApp': 'موافق على تذكيرات واتساب',
  'detail.noOptIn': 'بدون موافقة واتساب',
  'detail.periodic': 'زبون دوري',
  'detail.failedAttempts.one': 'محاولة فاشلة واحدة',
  'detail.failedAttempts.two': 'محاولتان فاشلتان',
  'detail.failedAttempts.few': '{count} محاولات فاشلة',
  'detail.failedAttempts.many': '{count} محاولة فاشلة',
  'detail.failedAttempts.other': '{count} محاولة فاشلة',
  'detail.lastOn': 'آخرها في {date}',
  'detail.noFailureYet': 'لم تفشل أي محاولة بعد.',
  'detail.noFailures': 'لا محاولات فاشلة.',
  'detail.historyFailed': 'تعذّر تحميل السجل.',
  'detail.vehicles': 'المركبات',
  'detail.addVehicle': 'إضافة مركبة',
  'detail.noVehicles': 'لا مركبات مسجّلة.',
  'detail.noPlate': 'بدون لوحة',
  'detail.noVehicleDetails': 'مركبة، بدون تفاصيل',
  'detail.jobHistory': 'سجل الأوامر',
  'detail.noJobs': 'لا أوامر بعد.',
  'detail.jobPrefix': 'أمر #',
  'detail.pendingReminders': 'تذكيرات معلّقة',
  'detail.noneScheduled': 'لا شيء مجدول.',
  'detail.unknownService': 'خدمة غير معروفة',
  'detail.noDuePoint': 'بدون موعد استحقاق',
  'detail.mutes': 'التذكيرات المكتومة',
  'detail.muteAction': 'كتم تذكير',
  'detail.muteNote': 'الكتم يسكت نوعًا واحدًا من الرسائل، وهو منفصل عن موافقة واتساب أعلاه التي تعني القبول بالتواصل أساسًا.',
  'detail.nothingMuted': 'لا شيء مكتوم.',
  'detail.allReminders': 'كل التذكيرات',
  'detail.mutedOn': 'كُتم في {date}',
  'detail.unmute': 'إلغاء الكتم',
  'detail.unmuting': 'جاري الإلغاء…',
  // ── reminders screen ───────────────────────────────────────────────────
  'reminders.loading': 'جاري تحميل التذكيرات…',
  'reminders.filterLabel': 'تصفية',
  'reminders.all': 'الكل',
  'reminders.overdue': 'متأخرة',
  'reminders.thisWeek': 'هذا الأسبوع',
  'reminders.nextWeek': 'الأسبوع القادم',
  'reminders.later': 'لاحقًا',
  'reminders.dismissed': 'متجاهَلة',
  'reminders.dueNow': 'مستحقة الآن',
  'reminders.dueCount.one': 'تذكير واحد مستحق',
  'reminders.dueCount.two': 'تذكيران مستحقان',
  'reminders.dueCount.few': '{count} تذكيرات مستحقة',
  'reminders.dueCount.many': '{count} تذكيرًا مستحقًا',
  'reminders.dueCount.other': '{count} تذكير مستحق',
  'reminders.nothingDue': 'لا شيء مستحق.',
  'reminders.furtherOut': 'قادمة لاحقًا',
  'reminders.pending': 'معلّقة',
  'reminders.nothingElse': 'لا شيء آخر قادم.',
  'reminders.showingFirst': 'عرض أول {count}',
  'reminders.dismissedNote': 'تذكيرات أُلغيت يدويًا ولا بديل حي لها.',
  'reminders.nothingDismissed': 'لا شيء متجاهَل.',
  'reminders.restore': 'استعادة',
  'reminders.unknownService': 'خدمة غير معروفة',
  'reminders.dueAt': 'مستحق عند {km} كم',
  'reminders.dueAtNow': 'مستحق عند {km} كم، حاليًا {now}',
  'reminders.dueOn': 'مستحق في {date}',
  'reminders.noDuePoint': 'بدون موعد',
  'reminders.badDistance': 'مسافة غير صالحة.',
  'reminders.needDuePoint': 'حدد مسافة أو تاريخًا أو كليهما.',
  'reminders.dueAtLabel': 'مستحق عند (كم)',
  'reminders.dueByLabel': 'مستحق بتاريخ',
  'reminders.dueEditNote': 'الحفظ يحدّث بند الأمر الذي جاء منه هذا التذكير.',
  'reminders.saveDue': 'حفظ الاستحقاق',
  'reminders.markSent': 'تم الإرسال',
  'reminders.couldntReach': 'تعذّر الوصول',
  'reminders.editDue': 'تعديل الاستحقاق',
  'reminders.dismiss': 'تجاهل',
  'reminders.undo': 'تراجع',
  'reminders.dismissedState': 'تم التجاهل',
  'reminders.whatHappened': 'ماذا حدث؟',
  'reminders.whatHappenedPlaceholder': 'لا يرد على الهاتف',
  'reminders.failNote': 'يبقى التذكير معلّقًا لإعادة المحاولة.',
  'reminders.logAttempt': 'تسجيل المحاولة',
  'reminders.cannotMessage': 'بدون موافقة واتساب لا يمكن الإرسال برسالة. اتصل بهم ثم علّم كمُرسَل.',
  // ── jobs screen ────────────────────────────────────────────────────────
  'jobs.customer': 'الزبون',
  'jobs.allCustomers': 'كل الزبائن',
  'jobs.from': 'من',
  'jobs.to': 'إلى',
  'jobs.clearFilters': 'مسح التصفية',
  'jobs.loading': 'جاري تحميل الأوامر…',
  'jobs.noMatch': 'لا أوامر مطابقة.',
  'jobs.unknownCustomer': 'زبون غير معروف',
  'jobs.lines.one': 'بند واحد',
  'jobs.lines.two': 'بندان',
  'jobs.lines.few': '{count} بنود',
  'jobs.lines.many': '{count} بندًا',
  'jobs.lines.other': '{count} بند',
  'jobs.editedOn': 'عُدّل في {date}',
  'jobs.listCapped': 'يعرض أحدث {count} أمر — ضيّق التصفية لرؤية الأقدم.',

  'jobEdit.title': 'أمر عمل #{n}',
  'jobEdit.vehicle': 'المركبة',
  'jobEdit.noVehicle': 'بدون مركبة',
  'jobEdit.odometer': 'العداد',
  'jobEdit.paymentMethod': 'طريقة الدفع',
  'jobEdit.lines': 'البنود',
  'jobEdit.loadingLines': 'جاري تحميل البنود…',
  'jobEdit.noLines': 'لا بنود.',
  'jobEdit.service': 'الخدمة',
  'jobEdit.unknownService': 'خدمة غير معروفة',
  'jobEdit.chooseService': 'اختر خدمة',
  'jobEdit.chooseServiceHint': 'ابحث في الدليل أو أنشئ خدمة جديدة.',
  'jobEdit.subcontracted': 'مقاول: {name}',
  'jobEdit.nextDueAt': 'الاستحقاق التالي (كم)',
  'jobEdit.nextDueBy': 'الاستحقاق التالي بتاريخ',
  'jobEdit.noReminderBlank': 'حقلا الاستحقاق فارغان، فلن يُنشأ تذكير لهذا البند.',
  'jobEdit.noReminderNoVehicle': 'هذا الأمر بلا مركبة، فلا تذكير لهذا البند. ربط مركبة يُنشئه.',
  'jobEdit.addLine': 'إضافة بند',
  'jobEdit.badOdometer': 'قراءة عداد غير صالحة.',
  'jobEdit.someFailed': 'بعض التغييرات لم تُحفظ:',
  'jobEdit.failedJobDetails': 'تفاصيل الأمر',
  'jobEdit.failedRemoving': 'إزالة {what}',
  'jobEdit.failedNewLines': 'البنود الجديدة',
  'jobEdit.aLine': 'بند',
  'jobEdit.deleteJob': 'حذف الأمر',
  'jobEdit.deleteConfirm': 'حذف هذا الأمر نهائيًا مع كل بنوده؟',
  'jobEdit.deletePermanently': 'حذف نهائي',
  'jobEdit.keep': 'إبقاء',
  'jobEdit.checking': 'جاري التحقق…',

  'vehicleChange.removeTitle': 'إزالة المركبة من الأمر؟',
  'vehicleChange.moveTitle': 'نقل الأمر إلى مركبة أخرى؟',
  'vehicleChange.previousVehicle': 'المركبة السابقة',
  'vehicleChange.noneRaised': 'لا تذكيرات من بنود هذا الأمر.',
  'vehicleChange.cancelled.one': 'سيُلغى تذكير واحد.',
  'vehicleChange.cancelled.two': 'سيُلغى تذكيران.',
  'vehicleChange.cancelled.few': 'ستُلغى {count} تذكيرات.',
  'vehicleChange.cancelled.many': 'سيُلغى {count} تذكيرًا.',
  'vehicleChange.cancelled.other': 'سيُلغى {count} تذكير.',
  'vehicleChange.moving.one': 'سينتقل تذكير واحد.',
  'vehicleChange.moving.two': 'سينتقل تذكيران.',
  'vehicleChange.moving.few': 'ستنتقل {count} تذكيرات.',
  'vehicleChange.moving.many': 'سينتقل {count} تذكيرًا.',
  'vehicleChange.moving.other': 'سينتقل {count} تذكير.',
  'vehicleChange.reads': 'قراءتها {km} كم',
  'vehicleChange.jobRecords': 'قراءة هذا الأمر {km} كم',
  'vehicleChange.withoutJob': 'بدون هذا الأمر: {km} كم',
  'vehicleChange.notRolledBack': 'قراءة المركبة السابقة لا تُسترجع تلقائيًا — قد تكون أُدخلت يدويًا.',
  'vehicleChange.editVehicle': 'تعديل {label}',
  'vehicleChange.removeAndSave': 'إزالة وحفظ',
  'vehicleChange.moveAndSave': 'نقل وحفظ',
  'vehicleChange.notRecorded': 'غير مسجّلة',
  // ── new job flow ───────────────────────────────────────────────────────
  'newJob.stepCustomer': 'الزبون',
  'newJob.stepVehicle': 'المركبة',
  'newJob.stepServices': 'الخدمات',
  'newJob.stepPayment': 'الدفع',
  'newJob.steps': 'خطوات إنشاء الأمر',
  'newJob.loadFailed': 'تعذّر التحميل.',
  'newJob.badOdometer': 'قراءة عداد غير صالحة.',
  'newJob.jobSaveFailed': 'تعذّر حفظ الأمر.',
  'newJob.linesFailed': 'أُنشئ الأمر لكن تعذّر حفظ بنوده. أعد الإرسال لإعادة محاولة البنود.',
  'newJob.savedFor': 'حُفظ الأمر لـ{name}',
  'newJob.thisCustomer': 'هذا الزبون',
  'newJob.savedTotal': 'الإجمالي {total}',
  'newJob.startAnother': 'أمر جديد آخر',
  'newJob.newCustomer': '+ زبون جديد',
  'newJob.noCustomers': 'لا زبائن بعد — أنشئ أول زبون.',
  'newJob.noCustomerMatch': 'لا زبون يطابق "{q}".',
  'newJob.noVehicleForJob': 'بدون مركبة لهذا الأمر',
  'newJob.roadside': 'خدمة طريق أو بيع مباشر',
  'newJob.addVehicle': '+ إضافة مركبة',
  'newJob.loadingVehicles': 'جاري تحميل المركبات…',
  'newJob.odometerToday': 'قراءة العداد اليوم',
  'newJob.newService': 'خدمة جديدة',
  'newJob.noLines': 'لا بنود بعد.',
  'newJob.chooseService': 'اختر خدمة',
  'newJob.chooseServiceHint': 'ابحث في الدليل أو أنشئ خدمة جديدة.',
  'newJob.nextDueAt': 'الاستحقاق التالي (كم)',
  'newJob.nextDueBy': 'الاستحقاق التالي بتاريخ',
  'newJob.noReminderBlank': 'حقلا الاستحقاق فارغان، فلن يُنشأ تذكير لهذا البند.',
  'newJob.noReminderNoVehicle': 'هذا الأمر بلا مركبة، فلا تذكير لهذا البند. ربط مركبة يُنشئه.',
  'newJob.addLine': 'إضافة بند',
  'newJob.paymentMethod': 'طريقة الدفع',
  'newJob.summary': 'الملخص',
  'newJob.summaryCustomer': 'الزبون',
  'newJob.summaryVehicle': 'المركبة',
  'newJob.summaryOdometer': 'العداد',
  'newJob.noServiceLines': 'بدون بنود خدمات.',
  'newJob.serviceFallback': 'خدمة',
  'newJob.linesTotal': 'الإجمالي',
  'newJob.taxNote': 'قبل الضريبة.',
  'newJob.back': 'رجوع',
  'newJob.continue': 'متابعة',
  'newJob.save': 'حفظ الأمر',
  'newJob.retryLines': 'إعادة محاولة البنود',
  'newJob.pickCustomer': 'اختر زبونًا للمتابعة.',
  'newJob.noVehicleDetails': 'مركبة، بدون تفاصيل',
  'newJob.emptyValue': '—',

  // ── service edit ──
  'serviceForm.editTitle': '',
  'serviceForm.otherNameEn': '',
  'serviceForm.otherNameAr': '',
  'serviceForm.otherNameHint': '',
  'serviceForm.otherNameNote': '',
  'serviceForm.deactivate': '',
  'serviceForm.deactivating': '',
  'serviceForm.deactivateNote': '',
  'serviceForm.deactivateFailed': '',
  'serviceForm.delete': '',
  'serviceForm.deleteConfirm': '',
  'serviceForm.deletePermanently': '',
  'serviceForm.deleteFailed': '',
  'serviceForm.checkingUse': '',
  'serviceForm.refJobLines.one': '',
  'serviceForm.refJobLines.other': '',
  'serviceForm.refReminders.one': '',
  'serviceForm.refReminders.other': '',
  'serviceForm.refMutes.one': '',
  'serviceForm.refMutes.other': '',
  'serviceForm.refParts.one': '',
  'serviceForm.refParts.other': '',
  'serviceForm.blocked': '',
  'serviceForm.checkFailed': '',
  'services.missingArabic.one': '',
  'services.missingArabic.other': '',
  'services.showAll': '',
  'services.onlyMissingArabic': '',
}
