/**
 * The English catalogue, and the source of truth for what keys exist —
 * StringKey is derived from it, and every other locale is checked against it.
 *
 * Data-derived text is deliberately absent: name_en, service_en, category and
 * the rest come from the database, which carries its own Arabic columns.
 * Developer-facing text — console diagnostics and the startup configuration
 * error — is also absent, since it is never shown to shop staff.
 *
 * Plural keys come in `base.one` / `base.other` sets, matching CLDR category
 * names so Intl.PluralRules can select between them. A locale needing more
 * categories adds `base.zero`, `base.two`, `base.few` or `base.many`.
 */
export const en = {
  // ── shell ─────────────────────────────────────────────────────────────
  'nav.sections': 'Sections',
  'nav.menu': 'Menu',
  'nav.brandHome': 'GRAND PRIX \u2014 Dashboard',
  'nav.dashboard': 'Dashboard',
  'nav.newJob': 'New job',
  'nav.jobs': 'Jobs',
  'nav.customers': 'Customers',
  'nav.reminders': 'Reminders',
  'nav.services': 'Services',
  'nav.stats': 'Stats',
  'brand.name': 'GRAND PRIX',
  'brand.alt': 'Grand Prix',
  'nav.language': 'Language',

  'app.loading': 'Loading…',
  'app.signOut': 'Sign out',
  'app.signingOut': 'Signing out…',
  'app.noStaffTitle': 'No staff record',
  'app.noStaffBody':
    '{email} is not linked to a staff record yet. Ask an admin to add you.',

  // ── sign in ───────────────────────────────────────────────────────────
  'login.title': 'Sign in',
  'login.subtitle': 'Shop staff only.',
  'login.email': 'Email',
  'login.password': 'Password',
  'login.submit': 'Sign in',
  'login.submitting': 'Signing in…',
  'login.needBoth': 'Enter your email and password.',
  'login.needEmail': 'Enter your email.',
  'login.needPassword': 'Enter your password.',

  // ── shared actions and states ─────────────────────────────────────────
  'action.close': 'Close',
  'action.cancel': 'Cancel',
  'action.change': 'Change',
  'action.edit': 'Edit',
  'action.remove': 'Remove',
  'action.saveChanges': 'Save changes',
  'action.saving': 'Saving…',
  'action.tryAgain': 'Try again',
  'action.seeAll': 'See all',
  'common.optional': 'optional',
  'common.notRecorded': 'Not recorded',
  'common.notSet': 'Not set',
  'common.km': 'km',
  'common.suggested': 'suggested',
  // ── lib: vehicles, odometer, contact health, periods ───────────────────
  'customer.unnamed': 'Unnamed',
  'vehicle.noPlate': 'Vehicle, no plate',
  'vehicle.notLinked': 'No vehicle linked',
  'vehicle.numbered': 'vehicle {number}',
  'vehicle.numberedNamed': 'vehicle {number} ({label})',
  'vehicle.badYear': 'Year must be a whole number, or left blank.',
  'vehicle.badOdometer': 'Odometer must be a whole number, or left blank.',
  'openJob.createFailed': 'The job could not be started.',
  'openJob.saveFailed': 'That change could not be saved.',
  'openJob.lineFailed': 'That line could not be saved.',
  'openJob.deleteRefused':
    'That job is no longer in progress, so it was left alone. Reload to see where it got to.',
  'vehicle.badKmPerDay':
    'Km a day must be a whole number above zero, or left blank.',

  'odometer.lower':
    'Lower than the reading on file. Legitimate after a cluster replacement, but usually a typo.',
  'odometer.jump':
    'More than 100,000 km above the reading on file. Usually one digit too many.',

  'contact.failed': 'Last attempt failed',
  'contact.noPhone': 'No phone number',
  'contact.noOptIn': 'No WhatsApp opt-in',

  'period.thisMonth': 'This month',
  'period.last3Months': 'Last 3 months',
  'period.thisYear': 'This year',
  'period.allTime': 'All time',

  'month.1': 'Jan',
  'month.2': 'Feb',
  'month.3': 'Mar',
  'month.4': 'Apr',
  'month.5': 'May',
  'month.6': 'Jun',
  'month.7': 'Jul',
  'month.8': 'Aug',
  'month.9': 'Sep',
  'month.10': 'Oct',
  'month.11': 'Nov',
  'month.12': 'Dec',
  // ── line editors: prices, fluid, tires ─────────────────────────────────
  'price.parts': 'Parts',
  'price.labour': 'Labour',
  'price.sub': 'Sub',
  'price.subcontractor': 'Subcontractor',
  'sub.title': 'New subcontractor',
  'sub.nameEn': 'Name in English',
  'sub.nameAr': 'Name in Arabic',
  'sub.nameHint': 'either name is enough',
  'sub.placeholderEn': 'Amman Radiator Works',
  'sub.placeholderAr': 'ورشة عمّان للردييتر',
  'sub.findingEn': 'Finding the English spelling…',
  'sub.findingAr': 'Finding the Arabic spelling…',
  'sub.add': 'Add subcontractor',
  'sub.unknown': 'No longer listed',
  'sub.needName': 'Enter the name.',
  'sub.note': 'Added to the shared list, so it is available on every job afterwards.',
  'sub.save': 'Save subcontractor',
  'sub.saving': 'Saving…',
  'sub.saveFailed': 'The subcontractor could not be saved.',
  'price.lineTotal': 'Line total',

  'fluid.type': 'Type',
  'fluid.grade': 'Grade',
  'fluid.brand': 'Brand',
  'fluid.quantity': 'Quantity',

  'tire.quantity': 'Quantity',
  'tire.brand': 'Brand',
  'tire.size': 'Size',
  'tire.sizePlaceholder': '225/50/17',
  'tire.dot': 'DOT',
  'tire.dotHint': 'year',
  'tire.dotPlaceholder': '2025',
  'tire.condition': 'Condition',
  'tire.runFlat': 'Run-flat',
  'tire.fittedBefore': 'fitted before',
  'tire.lastFitted': 'last fitted {brand}',

  // ── vehicle form ───────────────────────────────────────────────────────
  'vehicleForm.plate': 'Plate',
  'vehicleForm.platePlaceholder': '21-45678',
  'vehicleForm.vin': 'VIN',
  'vehicleForm.make': 'Make',
  'vehicleForm.model': 'Model',
  'vehicleForm.year': 'Year',
  'vehicleForm.yearPlaceholder': '2019',
  'vehicleForm.category': 'Category',
  'vehicleForm.odometer': 'Odometer',
  'vehicleForm.odometerPlaceholder': '84210',
  'vehicleForm.kmPerDay': 'How many km a day does the car do, on average?',
  'vehicleForm.kmPerDayNote':
    'A rough answer is enough. It turns an oil grade\u2019s distance into a date — without it, only the months apply.',
  'vehicleForm.addMake': 'Add a make',
  'vehicleForm.modelSuggestions': 'Model suggestions',
  'vehicleForm.loadingModels': 'Finding this make\u2019s models\u2026',
  'vehicleForm.newTitle': 'New vehicle',
  'vehicleForm.editTitle': 'Edit vehicle',
  'vehicleForm.save': 'Save vehicle',
  'vehicleForm.needSomething': 'Fill in at least one field.',
  'vehicleForm.saveFailed': 'The vehicle could not be saved.',

  // ── add make ───────────────────────────────────────────────────────────
  'make.title': 'New make',
  'make.label': 'Make',
  'make.placeholder': 'Land Rover',
  'make.needName': 'Enter the make.',
  'make.needLatin': 'Use Latin letters or digits for the make.',
  'make.note': 'Added to the shared list, so it is available everywhere afterwards.',
  'make.save': 'Save make',
  'make.saving': 'Saving…',
  // ── odometer hint ──────────────────────────────────────────────────────
  'odoHint.none': 'No odometer reading on this job or its vehicle.',
  'odoHint.onJob': 'on this job',
  'odoHint.onVehicle': 'on the vehicle',
  'odoHint.nowAt': 'Now at {km} km',

  // ── grade due hint ─────────────────────────────────────────────────────
  'gradeDue.interval': '{grade}: every {km} km or {months}.',
  'gradeDue.intervalKm': '{grade}: every {km} km.',
  'gradeDue.intervalMonths': '{grade}: every {months}.',
  'gradeDue.byUsage':
    'At {perDay} km a day, {distance} km is {days}, which comes first — next due {date}.',
  'gradeDue.byUsageEntered':
    'At {perDay} km a day, the {distance} km entered here is {days}, which comes first — next due {date}.',
  'gradeDue.byMonths':
    'At {perDay} km a day, {distance} km takes {days}, so the months come first — next due {date}.',
  'gradeDue.byMonthsEntered':
    'At {perDay} km a day, the {distance} km entered here takes {days}, so the months come first — next due {date}.',
  'gradeDue.noUsage':
    'No km a day on this car, so only the months apply — next due {date}.',
  'gradeDue.monthsOnly': 'Only the months apply — next due {date}.',
  'gradeDue.backwardsNote':
    'The next-due reading is not ahead of this job\u2019s, so there is no distance to measure.',
  'gradeDue.noDate':
    'No date to compute from — that needs months on the grade, or km a day on the car.',
  'gradeDue.due': 'Next due {date}.',
  'gradeDue.usageLabel': 'Km a day for this car.',
  'gradeDue.usageOnCar': 'saved on the car',
  'gradeDue.offerUsage': '{distance} km at {perDay} km/day → {date}',
  'gradeDue.offerMonths': '{months} → {date}',
  'gradeDue.useComputed': 'Use this date',
  'gradeDue.months.one': '{count} month',
  'gradeDue.months.other': '{count} months',
  'gradeDue.days.one': '{count} day',
  'gradeDue.days.other': '{count} days',

  // ── mutes ──────────────────────────────────────────────────────────────
  'mute.title': 'Mute reminders',
  'mute.scope': 'What to mute',
  'mute.scopeService': 'One service',
  'mute.scopeAll': 'Every reminder for this customer',
  'mute.service': 'Service',
  'mute.chooseService': 'Choose a service',
  'mute.needService': 'Choose the service to mute.',
  'mute.reason': 'Reason',
  'mute.reasonPlaceholder': 'Asked us not to',
  'mute.note': 'Muting cancels any reminder of this kind that is already pending.',
  'mute.nothingLeft':
    'This customer has nothing pending left to mute service by service. Muting everything still covers reminders raised later.',
  'mute.allDone':
    'Everything is already muted for this customer. Unmute something first to change it.',
  'mute.blanketInPlace':
    'A blanket mute is already in place for this customer, so only individual services can be added.',
  'mute.alreadyAll': 'Everything is already muted for this customer.',
  'mute.submit': 'Mute',
  'mute.submitting': 'Muting…',

  // ── customer form ──────────────────────────────────────────────────────
  'customerForm.newTitle': 'New customer',
  'customerForm.editTitle': 'Edit customer',
  'customerForm.nameEn': 'Name in English',
  'customerForm.nameEnHint': 'either name is enough',
  'customerForm.nameEnPlaceholder': 'Yousef Haddad',
  'customerForm.nameAr': 'Name in Arabic',
  'customerForm.nameArHint': 'either name is enough',
  'customerForm.nameArPlaceholder': 'يوسف حداد',
  'customerForm.findingEn': 'Finding the English spelling\u2026',
  'customerForm.findingAr': 'Finding the Arabic spelling\u2026',
  'customerForm.movedHere': 'moved here',
  'customerForm.phone': 'Phone',
  'customerForm.phoneHint': 'needed for reminders',
  'customerForm.phonePlaceholder': '079 000 0000',
  'customerForm.optIn': 'Happy to receive WhatsApp reminders',
  'customerForm.periodic': 'Comes in on a regular schedule',
  'customerForm.source': 'Source',
  'customerForm.sourceHint': 'how they found the shop',
  'customerForm.notes': 'Notes',
  'customerForm.needIdentity': 'A customer needs at least a name or a phone number.',
  'customerForm.saveFailed': 'The customer could not be saved.',
  'customerForm.changesFailed': 'The changes could not be saved.',
  'customerForm.save': 'Save customer',
  'customerForm.retryVehicles': 'Retry vehicles',
  'customerForm.vehicleLegend': 'Vehicle {number}',
  'customerForm.vehicleSaved': 'Saved',
  'customerForm.addAnotherVehicle': 'Add another vehicle',
  'customerForm.vehiclesFailed.one': 'one vehicle',
  'customerForm.vehiclesFailed.other': '{count} vehicles',
  'customerForm.partialSave':
    '{customer} was saved, but {failed} could not be added — {reasons}. Fix and submit again to retry just those.',
  // ── service form and picker ────────────────────────────────────────────
  'serviceForm.title': 'New service',
  'serviceForm.titleInCategory': 'New service · {category}',
  'serviceForm.category': 'Category',
  'serviceForm.chooseCategory': 'Choose a category',
  'serviceForm.needCategory': 'Choose a category.',
  'serviceForm.translateEmpty': 'The translation service returned nothing usable.',
  'serviceForm.namePlaceholder': 'Radiator flush',
  'serviceForm.name': 'Service name',
  'serviceForm.needName': 'Enter a service name.',
  'serviceForm.englishName': 'English name',
  'serviceForm.englishNameHint': 'required by the catalogue',
  'serviceForm.needEnglish': 'Add an English name to save.',
  'serviceForm.translateFailed':
    'Could not translate that name: {reason} Add an English name to save it.',
  'serviceForm.price': 'Default price',
  'serviceForm.pricePlaceholder': '0.000',
  'serviceForm.badPrice': 'Default price must be a positive number, or left blank.',
  'serviceForm.remind': 'Schedule a reminder after this service',
  'serviceForm.intervalKm': 'Usual interval',
  'serviceForm.intervalMonths': 'Or',
  'serviceForm.months': 'months',
  'serviceForm.kmPlaceholder': '5000',
  'serviceForm.monthsPlaceholder': '6',
  'serviceForm.badInterval':
    'Distance and time must be whole numbers above zero, or left blank.',
  'serviceForm.needInterval': 'Give the reminder a distance, a time, or both.',
  'serviceForm.reminderNote':
    'Used to prefill the due point when this service is added to a job. The job line is what actually creates the reminder.',
  'serviceForm.usesFluid': 'This service uses a fluid',
  'serviceForm.fluidUnit': 'Measured in',
  'serviceForm.liters': 'Liters',
  'serviceForm.grams': 'Grams',
  'serviceForm.typeList': 'Type list',
  'serviceForm.noTypeList': 'No standard list',
  'serviceForm.gradeList': 'Grade list',
  'serviceForm.noGradeList': 'No grade list',
  'serviceForm.fluidNote':
    'Job lines for this service will ask for brand and quantity, plus a type or grade wherever a list is chosen.',
  'serviceForm.save': 'Save service',
  'serviceForm.saveFailed': 'The service could not be saved.',

  'servicePicker.title': 'Choose a service',
  'servicePicker.filterByCategory': 'Filter by category',
  'servicePicker.all': 'All',
  'servicePicker.search': 'Search services',
  'servicePicker.common': 'Common',
  'servicePicker.noMatch': 'No service matches.',

  // ── services screen ────────────────────────────────────────────────────
  'services.loading': 'Loading services…',
  'services.loadFailed': 'Could not load the service catalogue.',
  'services.catalogue': 'Service catalogue',
  'services.count.one': '{count} service',
  'services.count.other': '{count} services',
  'services.noCategories': 'No active service categories.',
  'services.emptyCategory': 'No services in this category yet.',
  'services.addTo': 'Add service to {category}',
  'services.reminderRule': 'Reminder: {rule}',
  'services.reminderNoInterval': 'Reminder: no interval set',
  'common.currency': 'JOD',
  'common.noPhone': 'No phone',
  'common.clearFilters': 'Clear filters',

  // ── dashboard ──────────────────────────────────────────────────────────
  'dash.loadFailed': 'Could not load the dashboard.',
  'dash.jobsToday': 'Jobs today',
  'dash.revenueThisMonth': 'Revenue this month',
  'dash.remindersDue': 'Reminders due',
  'dash.customers': 'Customers',
  'dash.recentJobs': 'Recent jobs',
  'dash.noJobs': 'No jobs yet.',
  'dash.noLines': 'No lines',
  'dash.nothingDue': 'Nothing due right now.',
  'dash.unknownCustomer': 'Unknown customer',
  'dash.unknownService': 'Unknown service',
  'dash.contactHealth': 'Contact health',
  'dash.contactHealthNote':
    'Reminders for these customers can never be sent as things stand.',

  // ── stats ──────────────────────────────────────────────────────────────
  'stats.period': 'Period',
  'stats.loadFailed': 'Could not load the figures.',
  'stats.revenue': 'Revenue',
  'stats.jobs': 'Jobs',
  'stats.averageJob': 'Average job',
  'stats.activeCustomers': 'Active customers',
  'stats.byCategory': 'Revenue by category',
  'stats.withRevenue': '{count} with revenue',
  'stats.noRevenue': 'No revenue in this period.',
  'stats.onlyOneCategory':
    'Only {category} has revenue in this period — {amount} {currency}.',
  'stats.overTime': 'Revenue over time',
  'stats.monthsWithJobs.one': '{count} month with jobs',
  'stats.monthsWithJobs.other': '{count} months with jobs',
  'stats.noJobsInPeriod': 'No jobs in this period.',
  'stats.onlyOneMonth':
    'Only one month with jobs so far ({month}) — a trend needs at least two.',
  'stats.topByRevenue': 'Top services by revenue',
  'stats.topByFrequency': 'Top services by frequency',
  'stats.shown': '{count} shown',
  'stats.noServices': 'No services in this period.',
  'stats.onlyOneService': 'Only {service} in this period.',
  'stats.timesDone': 'Times done',
  'stats.times.one': '{count} time',
  'stats.times.other': '{count} times',
  'stats.retention': 'New and returning customers',
  'stats.noneActive': 'No customers active in this period.',
  'stats.onlyOneActiveMonth':
    'Only one month of activity so far ({month}) — returning customers need a second.',
  'stats.new': 'New',
  'stats.returning': 'Returning',
  'stats.lapsed': 'Lapsed customers',
  'stats.lapsedNote': 'by lifetime revenue · not period-scoped',
  'stats.noLapsed': 'No lapsed customers.',
  'stats.daysSince': '{count} days since',
  // ── customers screen ───────────────────────────────────────────────────
  'customers.loading': 'Loading customers…',
  'customers.loadFailed': 'Could not load customers.',
  'customers.search': 'Search by name or phone',
  'customers.searchLabel': 'Search customers',
  'customers.make': 'Make',
  'customers.anyMake': 'Any make',
  'customers.contact': 'Contact',
  'customers.anyContact': 'Any state',
  'customers.canMessage': 'Can be messaged',
  'customers.noneMatch': 'No customers match these filters.',
  'customers.add': 'Add customer',
  'customers.none': 'No customers yet.',
  'customers.optedIn': 'Opted in',
  'customers.notOptedIn': 'No opt-in',
  'customers.vehicles.one': '{count} vehicle',
  'customers.vehicles.other': '{count} vehicles',
  'customers.jobs.one': '{count} job',
  'customers.jobs.other': '{count} jobs',

  'detail.noPhoneOnFile': 'No phone on file',
  'detail.since': 'Customer since {date}',
  'detail.optedInWhatsApp': 'Opted in to WhatsApp',
  'detail.noOptIn': 'No WhatsApp opt-in',
  'detail.periodic': 'Regular schedule',
  'detail.failedAttempts.one': '{count} failed attempt',
  'detail.failedAttempts.other': '{count} failed attempts',
  'detail.lastOn': ', last on {date}',
  'detail.noFailureYet': '. No failure recorded yet.',
  'detail.noFailures': 'No failed attempts recorded.',
  'detail.historyFailed': 'Could not load this customer\u2019s history.',
  'detail.vehicles': 'Vehicles',
  'detail.addVehicle': 'Add vehicle',
  'detail.noVehicles': 'No vehicle on file.',
  'detail.noPlate': 'No plate',
  'detail.noVehicleDetails': 'No details recorded',
  'detail.kmPerDay': '{km} km a day',
  'detail.jobHistory': 'Job history',
  'detail.noJobs': 'No jobs yet.',
  'detail.jobPrefix': 'Job',
  'detail.pendingReminders': 'Pending reminders',
  'detail.noneScheduled': 'None scheduled.',
  'detail.unknownService': 'Unknown service',
  'detail.noDuePoint': 'No due point set',
  'detail.mutes': 'Reminder mutes',
  'detail.muteAction': 'Mute a reminder',
  'detail.muteNote':
    'A mute silences one kind of message. It is separate from the WhatsApp opt-in above, which is consent to be contacted at all.',
  'detail.nothingMuted': 'Nothing muted.',
  'detail.allReminders': 'All reminders',
  'detail.mutedOn': 'Muted {date}',
  'detail.unmute': 'Unmute',
  'detail.unmuting': 'Unmuting…',
  // ── reminders screen ───────────────────────────────────────────────────
  'reminders.loading': 'Loading reminders…',
  'reminders.filterLabel': 'Filter reminders',
  'reminders.all': 'All',
  'reminders.overdue': 'Overdue',
  'reminders.thisWeek': 'This week',
  'reminders.nextWeek': 'Next week',
  'reminders.later': 'Later',
  'reminders.dismissed': 'Dismissed',
  'reminders.dueNow': 'Due now',
  'reminders.dueCount.one': '{count} reminder',
  'reminders.dueCount.other': '{count} reminders',
  'reminders.nothingDue': 'Nothing due right now.',
  'reminders.furtherOut': 'Reminders further out',
  'reminders.pending': 'pending',
  'reminders.nothingElse': 'Nothing else pending.',
  'reminders.showingFirst': 'Showing the first {shown} of {total}.',
  'reminders.dismissedNote':
    'Cancelled by hand and not replaced since. Restoring puts one back in the queue.',
  'reminders.nothingDismissed': 'Nothing dismissed.',
  'reminders.restore': 'Restore',
  'reminders.unknownService': 'Unknown service',
  'reminders.dueAt': 'Due at {km} km',
  'reminders.dueAtNow': 'Due at {km} km, now at {current}',
  'reminders.dueOn': 'Due {date}',
  'reminders.noDuePoint': 'No due point set',
  'reminders.badDistance': 'Distance must be a whole number above zero, or left blank.',
  'reminders.needDuePoint': 'Give the reminder a distance, a date, or both.',
  'reminders.dueAtLabel': 'Due at',
  'reminders.dueByLabel': 'Due by',
  'reminders.dueEditNote': 'Saving updates the job line this reminder came from.',
  'reminders.saveDue': 'Save due point',
  'reminders.markSent': 'Mark sent',
  'reminders.couldntReach': 'Couldn\u2019t reach',
  'reminders.editDue': 'Edit due',
  'reminders.dismiss': 'Dismiss',
  'reminders.undo': 'Undo',
  'reminders.dismissedState': 'Dismissed',
  'reminders.whatHappened': 'What happened',
  'reminders.whatHappenedPlaceholder': 'No answer',
  'reminders.failNote': 'The reminder stays pending, so it can be tried again.',
  'reminders.logAttempt': 'Log the attempt',
  'reminders.cannotMessage':
    'No WhatsApp opt-in, so this cannot go out by message. Phone them, then mark it sent.',
  // ── jobs screen ────────────────────────────────────────────────────────
  'jobs.customer': 'Customer',
  'jobs.allCustomers': 'All customers',
  'jobs.from': 'From',
  'jobs.to': 'To',
  'jobs.add': 'New job',
  'jobs.loading': 'Loading jobs…',
  'jobs.noMatch': 'No jobs match these filters.',
  'jobs.unknownCustomer': 'Unknown customer',
  'jobs.lines.one': '{count} line',
  'jobs.lines.other': '{count} lines',
  'jobs.editedOn': 'edited {date}',
  'jobs.openSection': 'In progress',
  'jobs.openHint':
    'Started at the counter and not finished. Resume to carry on, or discard to throw it away.',
  'jobs.resume': 'Resume',
  'jobs.discardJob': 'Discard',
  'jobs.discardTitle': 'Discard job #{number}?',
  'jobs.discardBody':
    'The job and everything entered on it are deleted for good.',
  'jobs.discardConfirm': 'Delete this job',
  'jobs.discardKeep': 'Keep it',
  'jobs.statusOpen': 'In progress',
  'jobs.noLinesYet': 'nothing entered yet',
  'jobs.startedOn': 'started {date}',
  'jobs.listCapped':
    'Showing the {limit} most recent jobs. Narrow the filters to see older ones.',

  'jobEdit.title': 'Job #{number}',
  'jobEdit.vehicle': 'Vehicle',
  'jobEdit.noVehicle': 'No vehicle',
  'jobEdit.odometer': 'Odometer',
  'jobEdit.paymentMethod': 'Payment method',
  'jobEdit.lines': 'Lines',
  'jobEdit.loadingLines': 'Loading lines…',
  'jobEdit.noLines': 'No lines on this job.',
  'jobEdit.service': 'Service',
  'jobEdit.unknownService': 'Unknown',
  'jobEdit.chooseService': 'Choose a service',
  'jobEdit.chooseServiceHint': 'Choose a service — this line will be skipped otherwise.',
  'jobEdit.nextDueAt': 'Next due at',
  'jobEdit.nextDueBy': 'Next due by',
  'jobEdit.noReminderBlank': 'Both due fields are empty, so this line carries no reminder.',
  'jobEdit.noReminderNoVehicle':
    'This job has no vehicle, so this line carries no reminder. Attaching one raises it.',
  'jobEdit.addLine': 'Add line',
  'jobEdit.badOdometer': 'Odometer must be a whole number, or left blank.',
  'jobEdit.someFailed': 'Some changes did not save — {reasons}.',
  'jobEdit.failedJobDetails': 'job details',
  'jobEdit.failedRemoving': 'removing lines',
  'jobEdit.failedNewLines': 'new lines',
  'jobEdit.aLine': 'a line',
  'jobEdit.deleteJob': 'Delete job',
  'jobEdit.deleteConfirm': 'Delete this job for good?',
  'jobEdit.deletePermanently': 'Delete permanently',
  'jobEdit.keep': 'Keep',
  'jobEdit.checking': 'Checking…',

  'vehicleChange.removeTitle': 'Remove {vehicle} from this job?',
  'vehicleChange.moveTitle': 'Move this job to {vehicle}?',
  'vehicleChange.previousVehicle': 'the previous vehicle',
  'vehicleChange.noneRaised': 'No pending reminders were raised by this job\u2019s lines.',
  'vehicleChange.cancelled.one':
    '{count} pending reminder raised by this job\u2019s lines will be cancelled.',
  'vehicleChange.cancelled.other':
    '{count} pending reminders raised by this job\u2019s lines will be cancelled.',
  'vehicleChange.moving.one': '{count} pending reminder will move from {from} to {to}.',
  'vehicleChange.moving.other': '{count} pending reminders will move from {from} to {to}.',
  'vehicleChange.reads': '{vehicle} reads',
  'vehicleChange.jobRecords': 'This job records',
  'vehicleChange.withoutJob': 'Without this job it would read',
  'vehicleChange.notRolledBack':
    'That reading is not rolled back — it may have been typed by hand. Change it yourself if it is wrong.',
  'vehicleChange.editVehicle': 'Edit {vehicle}',
  'vehicleChange.removeAndSave': 'Remove and save',
  'vehicleChange.moveAndSave': 'Move and save',
  'vehicleChange.notRecorded': 'not recorded',
  // ── new job flow ───────────────────────────────────────────────────────
  'newJob.stepCustomer': 'Customer',
  'newJob.stepVehicle': 'Vehicle',
  'newJob.stepServices': 'Services',
  'newJob.stepPayment': 'Payment',
  'newJob.steps': 'Job steps',
  'newJob.loadFailed': 'Could not load what this screen needs.',
  'newJob.badOdometer': 'Odometer must be a whole number, or left blank.',
  'newJob.jobSaveFailed': 'The job could not be saved.',
  'newJob.linesFailed':
    'Job #{number} was created, but its lines could not be saved: {reason}. Submit again to retry the lines.',
  'newJob.savedFor': 'Job #{number} saved for {customer}.',
  'newJob.thisCustomer': 'this customer',
  'newJob.savedTotal': 'Total {amount} — from the job totals view.',
  'newJob.startAnother': 'Start another job',
  'newJob.newCustomer': 'New customer',
  'newJob.noCustomers': 'No customers yet.',
  'newJob.changeCustomerTitle': 'Change the customer to {customer}?',
  'newJob.changeCustomerNewTitle': 'Change to a new customer?',
  'newJob.changeCustomerLines.one': 'Job #{number} has one line entered for {customer}.',
  'newJob.changeCustomerLines.other':
    'Job #{number} has {count} lines entered for {customer}.',
  'newJob.changeCustomerWhy': 'It is deleted for good, and a new job started.',
  'newJob.changeCustomerConfirm': 'Discard and start a new job',
  'newJob.jobNumber': 'Job #{number}',
  'newJob.jobOpened': 'Job #{number} is open. Everything from here is saved as you go.',
  'newJob.jobCreateFailed':
    'The job could not be started, so nothing is being saved yet.',
  'newJob.jobSaveFailedInline': 'The last change did not save.',
  'newJob.retryJob': 'Try again',
  'newJob.resumeTitle': 'Unfinished jobs',
  'newJob.resumeCount.one': 'One job was started and not finished.',
  'newJob.resumeCount.other': '{count} jobs were started and not finished.',
  'newJob.resumeAction': 'Resume',
  'newJob.resumeDismiss': 'Start a new one',
  'newJob.resumeLoadFailed': 'That job could not be opened.',
  'newJob.resumeNothing': 'nothing entered yet',
  'newJob.vehicleMissing':
    'The vehicle on this job is no longer on this customer. Pick one, or carry on without.',
  'newJob.complete': 'Complete job',
  'newJob.completing': 'Completing\u2026',
  'newJob.noCustomerMatch': 'No customer matches \u201C{query}\u201D.',
  'newJob.noVehicleForJob': 'No vehicle for this job',
  'newJob.roadside': 'Roadside or counter sale',
  'newJob.addVehicle': 'Add vehicle',
  'newJob.loadingVehicles': 'Loading vehicles…',
  'newJob.odometerToday': 'Odometer today',
  'newJob.newService': 'New service',
  'newJob.noLines': 'No lines yet.',
  'newJob.chooseService': 'Choose a service',
  'newJob.chooseServiceHint': 'Choose a service — this line will be skipped otherwise.',
  'newJob.nextDueAt': 'Next due at',
  'newJob.nextDueBy': 'Next due by',
  'newJob.noReminderBlank':
    'Both due fields are empty, so no reminder will be created for this line.',
  'newJob.noReminderNoVehicle':
    'No vehicle was picked for this job, so no reminder will be created. Go back to the vehicle step to add one.',
  'newJob.addLine': 'Add line',
  'newJob.paymentMethod': 'Payment method',
  'newJob.summary': 'Summary',
  'newJob.summaryCustomer': 'Customer',
  'newJob.summaryVehicle': 'Vehicle',
  'newJob.summaryOdometer': 'Odometer',
  'newJob.noServiceLines': 'No service lines.',
  'newJob.serviceFallback': 'Service',
  'newJob.linesTotal': 'Lines total',
  'newJob.taxNote':
    'Tax and discount are not applied here — the saved total comes from the job totals view.',
  'newJob.back': 'Back',
  'newJob.continue': 'Continue',
  'newJob.save': 'Save job',
  'newJob.retryLines': 'Retry lines',
  'newJob.pickCustomer': 'Pick a customer to continue.',
  'newJob.noVehicleDetails': 'No details recorded',
  'newJob.emptyValue': '—',

  // ── service edit ───────────────────────────────────────────────────────
  'serviceForm.editTitle': 'Edit service',
  'serviceForm.otherNameEn': 'English name',
  'serviceForm.otherNameAr': 'Arabic name',
  'serviceForm.otherNameHint': 'the other language',
  'serviceForm.otherNameNote':
    'Translations are written unreviewed, so a wrong one is corrected here rather than by switching the app language.',
  'serviceForm.deactivate': 'Deactivate',
  'serviceForm.deactivating': 'Deactivating…',
  'serviceForm.deactivateNote':
    'Hides it from the picker. Job lines that already use it are left alone.',
  'serviceForm.deactivateFailed': 'The service could not be deactivated.',
  'serviceForm.delete': 'Delete',
  'serviceForm.deleteConfirm': 'Delete this service for good?',
  'serviceForm.deletePermanently': 'Delete permanently',
  'serviceForm.deleteFailed': 'The service could not be deleted.',
  'serviceForm.checkingUse': 'Checking where it is used…',
  'serviceForm.refJobLines.one': 'Used on {count} job line',
  'serviceForm.refJobLines.other': 'Used on {count} job lines',
  'serviceForm.refReminders.one': 'Has a reminder',
  'serviceForm.refReminders.other': 'Has {count} reminders',
  'serviceForm.refMutes.one': 'Muted for one customer',
  'serviceForm.refMutes.other': 'Muted for {count} customers',
  'serviceForm.refParts.one': 'Has one part mapping',
  'serviceForm.refParts.other': 'Has {count} part mappings',
  'serviceForm.blocked':
    '{reason}, so it cannot be deleted. Deactivate it instead.',
  'serviceForm.checkFailed':
    'Could not check where this service is used, so deleting is not offered.',
  'services.missingArabic.one': '{count} without an Arabic name',
  'services.missingArabic.other': '{count} without an Arabic name',
  'services.showAll': 'Show all',
  'services.onlyMissingArabic': 'Only services with no Arabic name.',
} as const
