import type { Catalogue } from './strings'

/**
 * Arabic catalogue. Every key from the English catalogue is present with an
 * empty value; `t()` falls back to English for anything still empty, so an
 * unfinished translation shows English rather than a blank label.
 *
 * Plural sets may add 'base.zero', 'base.two', 'base.few' and 'base.many' —
 * Arabic uses all six CLDR categories. Intl.PluralRules picks the category and
 * falls back to 'base.other' when that category is absent.
 */
export const ar: Catalogue = {
  // ── shell ─────────────────────────────────────────────────────────────
  'nav.sections': '',
  'nav.dashboard': '',
  'nav.newJob': '',
  'nav.jobs': '',
  'nav.customers': '',
  'nav.reminders': '',
  'nav.services': '',
  'nav.stats': '',
  'brand.name': '',
  'brand.alt': '',
  'nav.language': '',

  'app.loading': '',
  'app.signOut': '',
  'app.signingOut': '',
  'app.noStaffTitle': '',
  'app.noStaffBody': '',

  // ── sign in ───────────────────────────────────────────────────────────
  'login.title': '',
  'login.subtitle': '',
  'login.email': '',
  'login.password': '',
  'login.submit': '',
  'login.submitting': '',
  'login.needBoth': '',
  'login.needEmail': '',
  'login.needPassword': '',

  // ── shared actions and states ─────────────────────────────────────────
  'action.close': '',
  'action.cancel': '',
  'action.change': '',
  'action.edit': '',
  'action.remove': '',
  'action.saveChanges': '',
  'action.saving': '',
  'action.tryAgain': '',
  'action.seeAll': '',
  'common.optional': '',
  'common.notRecorded': '',
  'common.notSet': '',
  'common.km': '',
  // ── lib: vehicles, odometer, contact health, periods ───────────────────
  'customer.unnamed': '',
  'vehicle.noPlate': '',
  'vehicle.notLinked': '',
  'vehicle.numbered': '',
  'vehicle.numberedNamed': '',
  'vehicle.badYear': '',
  'vehicle.badOdometer': '',

  'odometer.lower': '',
  'odometer.jump': '',

  'contact.failed': '',
  'contact.noPhone': '',
  'contact.noOptIn': '',

  'period.thisMonth': '',
  'period.last3Months': '',
  'period.thisYear': '',
  'period.allTime': '',

  'month.1': '',
  'month.2': '',
  'month.3': '',
  'month.4': '',
  'month.5': '',
  'month.6': '',
  'month.7': '',
  'month.8': '',
  'month.9': '',
  'month.10': '',
  'month.11': '',
  'month.12': '',
  // ── line editors: prices, fluid, tires ─────────────────────────────────
  'price.parts': '',
  'price.labour': '',
  'price.sub': '',
  'price.lineTotal': '',

  'fluid.type': '',
  'fluid.grade': '',
  'fluid.brand': '',
  'fluid.quantity': '',

  'tire.quantity': '',
  'tire.brand': '',
  'tire.size': '',
  'tire.sizePlaceholder': '',
  'tire.dot': '',
  'tire.dotHint': '',
  'tire.dotPlaceholder': '',
  'tire.condition': '',
  'tire.runFlat': '',
  'tire.fittedBefore': '',
  'tire.lastFitted': '',

  // ── vehicle form ───────────────────────────────────────────────────────
  'vehicleForm.plate': '',
  'vehicleForm.platePlaceholder': '',
  'vehicleForm.vin': '',
  'vehicleForm.make': '',
  'vehicleForm.model': '',
  'vehicleForm.year': '',
  'vehicleForm.yearPlaceholder': '',
  'vehicleForm.category': '',
  'vehicleForm.odometer': '',
  'vehicleForm.odometerPlaceholder': '',
  'vehicleForm.addMake': '',
  'vehicleForm.newTitle': '',
  'vehicleForm.editTitle': '',
  'vehicleForm.save': '',
  'vehicleForm.needSomething': '',
  'vehicleForm.saveFailed': '',

  // ── add make ───────────────────────────────────────────────────────────
  'make.title': '',
  'make.label': '',
  'make.placeholder': '',
  'make.needName': '',
  'make.needLatin': '',
  'make.note': '',
  'make.save': '',
  'make.saving': '',
  // ── odometer hint ──────────────────────────────────────────────────────
  'odoHint.none': '',
  'odoHint.onJob': '',
  'odoHint.onVehicle': '',
  'odoHint.nowAt': '',

  // ── mutes ──────────────────────────────────────────────────────────────
  'mute.title': '',
  'mute.scope': '',
  'mute.scopeService': '',
  'mute.scopeAll': '',
  'mute.service': '',
  'mute.chooseService': '',
  'mute.needService': '',
  'mute.reason': '',
  'mute.reasonPlaceholder': '',
  'mute.note': '',
  'mute.nothingLeft': '',
  'mute.allDone': '',
  'mute.blanketInPlace': '',
  'mute.alreadyAll': '',
  'mute.submit': '',
  'mute.submitting': '',

  // ── customer form ──────────────────────────────────────────────────────
  'customerForm.newTitle': '',
  'customerForm.editTitle': '',
  'customerForm.nameEn': '',
  'customerForm.nameEnHint': '',
  'customerForm.nameAr': '',
  'customerForm.nameArHint': '',
  'customerForm.phone': '',
  'customerForm.phoneHint': '',
  'customerForm.phonePlaceholder': '',
  'customerForm.optIn': '',
  'customerForm.periodic': '',
  'customerForm.source': '',
  'customerForm.sourceHint': '',
  'customerForm.notes': '',
  'customerForm.needIdentity': '',
  'customerForm.saveFailed': '',
  'customerForm.changesFailed': '',
  'customerForm.save': '',
  'customerForm.retryVehicles': '',
  'customerForm.vehicleLegend': '',
  'customerForm.vehicleSaved': '',
  'customerForm.addAnotherVehicle': '',
  'customerForm.vehiclesFailed.one': '',
  'customerForm.vehiclesFailed.other': '',
  'customerForm.partialSave': '',
  // ── service form and picker ────────────────────────────────────────────
  'serviceForm.title': '',
  'serviceForm.titleInCategory': '',
  'serviceForm.category': '',
  'serviceForm.chooseCategory': '',
  'serviceForm.needCategory': '',
  'serviceForm.name': '',
  'serviceForm.namePlaceholder': '',
  'serviceForm.needName': '',
  'serviceForm.price': '',
  'serviceForm.pricePlaceholder': '',
  'serviceForm.badPrice': '',
  'serviceForm.remind': '',
  'serviceForm.intervalKm': '',
  'serviceForm.intervalMonths': '',
  'serviceForm.months': '',
  'serviceForm.kmPlaceholder': '',
  'serviceForm.monthsPlaceholder': '',
  'serviceForm.badInterval': '',
  'serviceForm.needInterval': '',
  'serviceForm.reminderNote': '',
  'serviceForm.usesFluid': '',
  'serviceForm.fluidUnit': '',
  'serviceForm.liters': '',
  'serviceForm.grams': '',
  'serviceForm.typeList': '',
  'serviceForm.noTypeList': '',
  'serviceForm.gradeList': '',
  'serviceForm.noGradeList': '',
  'serviceForm.fluidNote': '',
  'serviceForm.save': '',
  'serviceForm.saveFailed': '',

  'servicePicker.title': '',
  'servicePicker.filterByCategory': '',
  'servicePicker.all': '',
  'servicePicker.search': '',
  'servicePicker.common': '',
  'servicePicker.noMatch': '',

  // ── services screen ────────────────────────────────────────────────────
  'services.loading': '',
  'services.loadFailed': '',
  'services.catalogue': '',
  'services.count.one': '',
  'services.count.other': '',
  'services.noCategories': '',
  'services.emptyCategory': '',
  'services.addTo': '',
  'services.reminderRule': '',
  'services.reminderNoInterval': '',
  'common.currency': '',
  'common.noPhone': '',

  // ── dashboard ──────────────────────────────────────────────────────────
  'dash.loadFailed': '',
  'dash.jobsToday': '',
  'dash.revenueThisMonth': '',
  'dash.remindersDue': '',
  'dash.customers': '',
  'dash.recentJobs': '',
  'dash.noJobs': '',
  'dash.noLines': '',
  'dash.nothingDue': '',
  'dash.unknownCustomer': '',
  'dash.unknownService': '',
  'dash.contactHealth': '',
  'dash.contactHealthNote': '',

  // ── stats ──────────────────────────────────────────────────────────────
  'stats.period': '',
  'stats.loadFailed': '',
  'stats.revenue': '',
  'stats.jobs': '',
  'stats.averageJob': '',
  'stats.activeCustomers': '',
  'stats.byCategory': '',
  'stats.withRevenue': '',
  'stats.noRevenue': '',
  'stats.onlyOneCategory': '',
  'stats.overTime': '',
  'stats.monthsWithJobs.one': '',
  'stats.monthsWithJobs.other': '',
  'stats.noJobsInPeriod': '',
  'stats.onlyOneMonth': '',
  'stats.topByRevenue': '',
  'stats.topByFrequency': '',
  'stats.shown': '',
  'stats.noServices': '',
  'stats.onlyOneService': '',
  'stats.timesDone': '',
  'stats.times.one': '',
  'stats.times.other': '',
  'stats.retention': '',
  'stats.noneActive': '',
  'stats.onlyOneActiveMonth': '',
  'stats.new': '',
  'stats.returning': '',
  'stats.lapsed': '',
  'stats.lapsedNote': '',
  'stats.noLapsed': '',
  'stats.daysSince': '',
  // ── customers screen ───────────────────────────────────────────────────
  'customers.loading': '',
  'customers.loadFailed': '',
  'customers.search': '',
  'customers.searchLabel': '',
  'customers.make': '',
  'customers.anyMake': '',
  'customers.add': '',
  'customers.none': '',
  'customers.noneWithMake': '',
  'customers.noMakeMatch': '',
  'customers.noMatch': '',
  'customers.optedIn': '',
  'customers.notOptedIn': '',
  'customers.vehicles.one': '',
  'customers.vehicles.other': '',
  'customers.jobs.one': '',
  'customers.jobs.other': '',

  'detail.noPhoneOnFile': '',
  'detail.since': '',
  'detail.optedInWhatsApp': '',
  'detail.noOptIn': '',
  'detail.periodic': '',
  'detail.failedAttempts.one': '',
  'detail.failedAttempts.other': '',
  'detail.lastOn': '',
  'detail.noFailureYet': '',
  'detail.noFailures': '',
  'detail.historyFailed': '',
  'detail.vehicles': '',
  'detail.addVehicle': '',
  'detail.noVehicles': '',
  'detail.noPlate': '',
  'detail.noVehicleDetails': '',
  'detail.jobHistory': '',
  'detail.noJobs': '',
  'detail.jobPrefix': '',
  'detail.pendingReminders': '',
  'detail.noneScheduled': '',
  'detail.unknownService': '',
  'detail.noDuePoint': '',
  'detail.mutes': '',
  'detail.muteAction': '',
  'detail.muteNote': '',
  'detail.nothingMuted': '',
  'detail.allReminders': '',
  'detail.mutedOn': '',
  'detail.unmute': '',
  'detail.unmuting': '',
  // ── reminders screen ───────────────────────────────────────────────────
  'reminders.loading': '',
  'reminders.filterLabel': '',
  'reminders.all': '',
  'reminders.overdue': '',
  'reminders.thisWeek': '',
  'reminders.nextWeek': '',
  'reminders.later': '',
  'reminders.dismissed': '',
  'reminders.dueNow': '',
  'reminders.dueCount.one': '',
  'reminders.dueCount.other': '',
  'reminders.nothingDue': '',
  'reminders.furtherOut': '',
  'reminders.pending': '',
  'reminders.nothingElse': '',
  'reminders.showingFirst': '',
  'reminders.dismissedNote': '',
  'reminders.nothingDismissed': '',
  'reminders.restore': '',
  'reminders.unknownService': '',
  'reminders.dueAt': '',
  'reminders.dueAtNow': '',
  'reminders.dueOn': '',
  'reminders.noDuePoint': '',
  'reminders.badDistance': '',
  'reminders.needDuePoint': '',
  'reminders.dueAtLabel': '',
  'reminders.dueByLabel': '',
  'reminders.dueEditNote': '',
  'reminders.saveDue': '',
  'reminders.markSent': '',
  'reminders.couldntReach': '',
  'reminders.editDue': '',
  'reminders.dismiss': '',
  'reminders.undo': '',
  'reminders.dismissedState': '',
  'reminders.whatHappened': '',
  'reminders.whatHappenedPlaceholder': '',
  'reminders.failNote': '',
  'reminders.logAttempt': '',
  'reminders.cannotMessage': '',
  // ── jobs screen ────────────────────────────────────────────────────────
  'jobs.customer': '',
  'jobs.allCustomers': '',
  'jobs.from': '',
  'jobs.to': '',
  'jobs.clearFilters': '',
  'jobs.loading': '',
  'jobs.noMatch': '',
  'jobs.unknownCustomer': '',
  'jobs.lines.one': '',
  'jobs.lines.other': '',
  'jobs.editedOn': '',
  'jobs.listCapped': '',

  'jobEdit.title': '',
  'jobEdit.vehicle': '',
  'jobEdit.noVehicle': '',
  'jobEdit.odometer': '',
  'jobEdit.paymentMethod': '',
  'jobEdit.lines': '',
  'jobEdit.loadingLines': '',
  'jobEdit.noLines': '',
  'jobEdit.service': '',
  'jobEdit.unknownService': '',
  'jobEdit.chooseService': '',
  'jobEdit.chooseServiceHint': '',
  'jobEdit.subcontracted': '',
  'jobEdit.nextDueAt': '',
  'jobEdit.nextDueBy': '',
  'jobEdit.noReminderBlank': '',
  'jobEdit.noReminderNoVehicle': '',
  'jobEdit.addLine': '',
  'jobEdit.badOdometer': '',
  'jobEdit.someFailed': '',
  'jobEdit.failedJobDetails': '',
  'jobEdit.failedRemoving': '',
  'jobEdit.failedNewLines': '',
  'jobEdit.aLine': '',
  'jobEdit.deleteJob': '',
  'jobEdit.deleteConfirm': '',
  'jobEdit.deletePermanently': '',
  'jobEdit.keep': '',
  'jobEdit.checking': '',

  'vehicleChange.removeTitle': '',
  'vehicleChange.moveTitle': '',
  'vehicleChange.previousVehicle': '',
  'vehicleChange.noneRaised': '',
  'vehicleChange.cancelled.one': '',
  'vehicleChange.cancelled.other': '',
  'vehicleChange.moving.one': '',
  'vehicleChange.moving.other': '',
  'vehicleChange.reads': '',
  'vehicleChange.jobRecords': '',
  'vehicleChange.withoutJob': '',
  'vehicleChange.notRolledBack': '',
  'vehicleChange.editVehicle': '',
  'vehicleChange.removeAndSave': '',
  'vehicleChange.moveAndSave': '',
  'vehicleChange.notRecorded': '',
  // ── new job flow ───────────────────────────────────────────────────────
  'newJob.stepCustomer': '',
  'newJob.stepVehicle': '',
  'newJob.stepServices': '',
  'newJob.stepPayment': '',
  'newJob.steps': '',
  'newJob.loadFailed': '',
  'newJob.badOdometer': '',
  'newJob.jobSaveFailed': '',
  'newJob.linesFailed': '',
  'newJob.savedFor': '',
  'newJob.thisCustomer': '',
  'newJob.savedTotal': '',
  'newJob.startAnother': '',
  'newJob.newCustomer': '',
  'newJob.noCustomers': '',
  'newJob.noCustomerMatch': '',
  'newJob.noVehicleForJob': '',
  'newJob.roadside': '',
  'newJob.addVehicle': '',
  'newJob.loadingVehicles': '',
  'newJob.odometerToday': '',
  'newJob.newService': '',
  'newJob.noLines': '',
  'newJob.chooseService': '',
  'newJob.chooseServiceHint': '',
  'newJob.nextDueAt': '',
  'newJob.nextDueBy': '',
  'newJob.noReminderBlank': '',
  'newJob.noReminderNoVehicle': '',
  'newJob.addLine': '',
  'newJob.paymentMethod': '',
  'newJob.summary': '',
  'newJob.summaryCustomer': '',
  'newJob.summaryVehicle': '',
  'newJob.summaryOdometer': '',
  'newJob.noServiceLines': '',
  'newJob.serviceFallback': '',
  'newJob.linesTotal': '',
  'newJob.taxNote': '',
  'newJob.back': '',
  'newJob.continue': '',
  'newJob.save': '',
  'newJob.retryLines': '',
  'newJob.pickCustomer': '',
  'newJob.noVehicleDetails': '',
  'newJob.emptyValue': '',
}
